development:
  adapter: postgresql
  database: sample_app_db
  host: localhost

test:
  adapter: postgresql
  database: sample_app_db
  host: localhost

production:
  adapter: postgresql
  database: sample_app_db
  host: localhost